version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ".:/project"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres:5432?sslmode=disable
      - HTTP_PORT=5000
    ports:
      - "5000:5000"
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/initial.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:6.0.9
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

volumes:
  postgres:
    driver: local
  redis:
    driver: local
